#!/bin/bash

if [ "$(cat $HOME/.bg_shuf/last)" == "light" ] && [ -f $HOME/.bg_shuf/dark ]; then
    bg=$(cat $HOME/.bg_shuf/dark);
else
    lastbg=$(if [ -f $HOME/.bg_shuf/dark ]; then cat ~/.bg_shuf/dark; else echo ""; fi);
    bg=$lastbg;
    while [ "$bg" == "$lastbg" ]; do
        bg=$(ls $HOME/.backgrounds/dark/ | shuf -n 1);
    done;
fi;
feh --bg-fill $HOME/.backgrounds/dark/$bg;
mkdir -p $HOME/.bg_shuf/;
echo "dark" > $HOME/.bg_shuf/last
echo $bg > $HOME/.bg_shuf/dark;
